M48
; DRILL file {KiCad (6.0.4)} date Mon Jun 27 13:40:29 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-27T13:40:29+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X5.1Y-3.2283
X5.1Y-6.7
X9.2Y-4.85
X9.2Y-6.7
X12.7Y-3.2283
X12.7Y-6.7
T0
M30
